# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Wed Feb 26 01:15:50 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from ControllerOverviewFrame import *
# end wxGlade


class AdminFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: AdminFrame.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.SetSize((400, 300))
		
		# Menu Bar
		self.frame_1_menubar = wx.MenuBar()
		wxglade_tmp_menu = wx.Menu()
		wxglade_tmp_menu.Append(wx.ID_ANY, "New Division", "")
		wxglade_tmp_menu.Append(wx.ID_ANY, "Open Division", "")
		self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
		wxglade_tmp_menu = wx.Menu()
		self.frame_1_menubar.Append(wxglade_tmp_menu, "Edit Division")
		wxglade_tmp_menu = wx.Menu()
		item = wxglade_tmp_menu.Append(wx.ID_ANY, "Setup", "")
		self.Bind(wx.EVT_MENU, self.open_controller_setup, id=item.GetId())
		self.frame_1_menubar.Append(wxglade_tmp_menu, "Controllers")
		wxglade_tmp_menu = wx.Menu()
		wxglade_tmp_menu.Append(wx.ID_ANY, "Pop Audience View", "")
		self.frame_1_menubar.Append(wxglade_tmp_menu, "Audience")
		self.SetMenuBar(self.frame_1_menubar)
		# Menu Bar end

		self.__set_properties()
		self.__do_layout()

		# end wxGlade

		wx.App.Get().controller_list = [None]*7

	def __set_properties(self):
		# begin wxGlade: AdminFrame.__set_properties
		self.SetTitle("poomsae-score-py 0.0.1")
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: AdminFrame.__do_layout
		sizer_7 = wx.BoxSizer(wx.VERTICAL)
		sizer_7.Add((0, 0), 0, 0, 0)
		self.SetSizer(sizer_7)
		self.Layout()
		# end wxGlade

	def open_controller_setup(self, event):  # wxGlade: AdminFrame.<event_handler>
		f = ControllerOverviewFrame(self)
		f.Show()

# end of class AdminFrame
