# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Tue Feb 25 20:33:13 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from ControllerConnectDialog import *
# end wxGlade

import threading
import time

class ConnectionButton(wx.Button):
	def __init__(self, *args, **kwds):
		wx.Button.__init__(self, *args, **kwds)
		self.c_num = -1

	def SetC_num(self, n):
		self.c_num = n


class ControllerOverviewFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: ControllerOverviewFrame.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.SetSize((487, 448))
		self.controller1_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c1_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller2_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c2_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller3_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c3_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller4_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c4_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller5_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c5_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller6_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c6_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.controller7_port = wx.StaticText(self, wx.ID_ANY, "NOT CONNECTED")
		self.c7_connection_button = ConnectionButton(self, wx.ID_ANY, "CONNECT")
		self.close_button = wx.Button(self, wx.ID_ANY, "Close")

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c1_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c2_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c3_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c4_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c5_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c6_connection_button)
		self.Bind(wx.EVT_BUTTON, self.open_connect_dialog, self.c7_connection_button)
		self.Bind(wx.EVT_BUTTON, self.Close, self.close_button)
		# end wxGlade
		self.Bind(wx.EVT_CLOSE, self.Close)

		self.continue_update = True
		self.update_thread = threading.Thread(target=self._update_thread)
		self.update_thread.daemon = True
		self.update_thread.start()


	def __set_properties(self):
		# begin wxGlade: ControllerOverviewFrame.__set_properties
		self.SetTitle("frame")
		self.c1_connection_button.SetC_num(0)
		self.c2_connection_button.SetC_num(1)
		self.c3_connection_button.SetC_num(2)
		self.c4_connection_button.SetC_num(3)
		self.c5_connection_button.SetC_num(4)
		self.c6_connection_button.SetC_num(5)
		self.c7_connection_button.SetC_num(6)
		# end wxGlade

		self.label_list = [
			self.controller1_port,
			self.controller2_port,
			self.controller3_port,
			self.controller4_port,
			self.controller5_port,
			self.controller6_port,
			self.controller7_port
		]
		self.button_list = [
			self.c1_connection_button,
			self.c2_connection_button,
			self.c3_connection_button,
			self.c4_connection_button,
			self.c5_connection_button,
			self.c6_connection_button,
			self.c7_connection_button,
		]

		for i in range(7):
			if wx.App.Get().controller_list[i] is not None:
				self.label_list[i].SetLabel('CONNECTED ({})'.format(wx.App.Get().controller_list[i].ser.port))
				self.button_list[i].Disable()
			else:
				self.label_list[i].SetLabel('NOT CONNECTED')
				self.button_list[i].Enable()


	def __do_layout(self):
		# begin wxGlade: ControllerOverviewFrame.__do_layout
		sizer_8 = wx.BoxSizer(wx.VERTICAL)
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_15 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 7"), wx.HORIZONTAL)
		sizer_14 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 6"), wx.HORIZONTAL)
		sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 5"), wx.HORIZONTAL)
		sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 4"), wx.HORIZONTAL)
		sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 3"), wx.HORIZONTAL)
		sizer_10 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 2"), wx.HORIZONTAL)
		sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Controller 1"), wx.HORIZONTAL)
		sizer_9.Add(self.controller1_port, 0, wx.ALIGN_CENTER, 0)
		sizer_9.Add(self.c1_connection_button, 0, 0, 0)
		sizer_9.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)
		sizer_10.Add(self.controller2_port, 0, 0, 0)
		sizer_10.Add(self.c2_connection_button, 0, 0, 0)
		sizer_10.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_11.Add(self.controller3_port, 0, 0, 0)
		sizer_11.Add(self.c3_connection_button, 0, 0, 0)
		sizer_11.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_11, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_12.Add(self.controller4_port, 0, 0, 0)
		sizer_12.Add(self.c4_connection_button, 0, 0, 0)
		sizer_12.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_13.Add(self.controller5_port, 0, 0, 0)
		sizer_13.Add(self.c5_connection_button, 0, 0, 0)
		sizer_13.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_13, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_14.Add(self.controller6_port, 0, 0, 0)
		sizer_14.Add(self.c6_connection_button, 0, 0, 0)
		sizer_14.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_14, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_15.Add(self.controller7_port, 0, 0, 0)
		sizer_15.Add(self.c7_connection_button, 0, 0, 0)
		sizer_15.Add((0, 0), 0, 0, 0)
		sizer_8.Add(sizer_15, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_6.Add(self.close_button, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_8.Add(sizer_6, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 10)
		self.SetSizer(sizer_8)
		self.Layout()
		# end wxGlade

	def open_connect_dialog(self, event):  # wxGlade: ControllerOverviewFrame.<event_handler>
		button = event.GetEventObject()
		print(button.c_num)
		self.last_called_button = button
		f = ControllerConnectDialog(self)
		f.Show()
		print(f)


	def _update_thread(self):
		while self.continue_update:
			self.__set_properties()
			time.sleep(1)

	def Close(self, event):  # wxGlade: ControllerOverviewFrame.<event_handler>
		self.continue_update = False
		self.Destroy()

# end of class ControllerOverviewFrame
