# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Tue Feb 25 20:33:13 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import serial.tools.list_ports
# end wxGlade


class ControllerConnectDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: ControllerConnectDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.list_box_1 = wx.ListBox(self, wx.ID_ANY, choices=["No Devices Found"], style=wx.LB_HSCROLL | wx.LB_SINGLE)
		self.cancel_button = wx.Button(self, wx.ID_ANY, "Cancel")
		self.confirm_button = wx.Button(self, wx.ID_ANY, "Connect")

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.connect_button, self.confirm_button)
		# end wxGlade


	def __set_properties(self):
		# begin wxGlade: ControllerConnectDialog.__set_properties
		self.SetTitle("dialog")
		# end wxGlade

		ports = serial.tools.list_ports.comports()
		if len(ports) > 1:
			self.list_box_1.InsertItems([p.description for p in ports], 0)

	def __do_layout(self):
		# begin wxGlade: ControllerConnectDialog.__do_layout
		sizer_16 = wx.BoxSizer(wx.VERTICAL)
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_16.Add(self.list_box_1, 1, wx.ALL | wx.EXPAND, 10)
		sizer_6.Add(self.cancel_button, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_6.Add(self.confirm_button, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_16.Add(sizer_6, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 10)
		self.SetSizer(sizer_16)
		sizer_16.Fit(self)
		self.Layout()
		# end wxGlade

	def connect_button(self, event):  # wxGlade: ControllerConnectDialog.<event_handler>
		print("Event handler 'connect_button' not implemented!")
		event.Skip()

# end of class ControllerConnectDialog
