# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Wed Feb 26 16:51:43 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ControllerConnectionStatusPanel(wx.Panel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: ControllerConnectionStatusPanel.__init__
		kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: ControllerConnectionStatusPanel.__set_properties
		pass
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: ControllerConnectionStatusPanel.__do_layout
		grid_sizer_1 = wx.FlexGridSizer(7, 2, 10, 10)
		label_5 = wx.StaticText(self, wx.ID_ANY, "label_5")
		grid_sizer_1.Add(label_5, 0, 0, 0)
		bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_1.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_1.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_1, 0, wx.SHAPED, 0)
		label_6 = wx.StaticText(self, wx.ID_ANY, "label_6")
		grid_sizer_1.Add(label_6, 0, 0, 0)
		bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_2.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_2.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_2, 0, wx.SHAPED, 0)
		label_7 = wx.StaticText(self, wx.ID_ANY, "label_7")
		grid_sizer_1.Add(label_7, 0, 0, 0)
		bitmap_3 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_3.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_3.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_3, 0, wx.SHAPED, 0)
		label_8 = wx.StaticText(self, wx.ID_ANY, "label_8")
		grid_sizer_1.Add(label_8, 0, 0, 0)
		bitmap_4 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_4.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_4.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_4, 0, wx.SHAPED, 0)
		label_9 = wx.StaticText(self, wx.ID_ANY, "label_9")
		grid_sizer_1.Add(label_9, 0, 0, 0)
		bitmap_5 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_5.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_5.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_5, 0, wx.SHAPED, 0)
		label_10 = wx.StaticText(self, wx.ID_ANY, "label_10")
		grid_sizer_1.Add(label_10, 0, 0, 0)
		bitmap_6 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_6.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_6.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_6, 0, wx.SHAPED, 0)
		label_11 = wx.StaticText(self, wx.ID_ANY, "label_11")
		grid_sizer_1.Add(label_11, 0, 0, 0)
		bitmap_7 = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
		bitmap_7.SetBackgroundColour(wx.Colour(255, 0, 0))
		bitmap_7.SetForegroundColour(wx.Colour(255, 0, 0))
		grid_sizer_1.Add(bitmap_7, 0, wx.SHAPED, 0)
		self.SetSizer(grid_sizer_1)
		grid_sizer_1.Fit(self)
		grid_sizer_1.AddGrowableRow(0)
		grid_sizer_1.AddGrowableRow(1)
		grid_sizer_1.AddGrowableRow(2)
		grid_sizer_1.AddGrowableRow(3)
		grid_sizer_1.AddGrowableRow(4)
		grid_sizer_1.AddGrowableRow(5)
		grid_sizer_1.AddGrowableRow(6)
		grid_sizer_1.AddGrowableCol(0)
		grid_sizer_1.AddGrowableCol(1)
		self.Layout()
		# end wxGlade

# end of class ControllerConnectionStatusPanel
