# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Tue Feb 25 20:33:13 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class NewDivDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: NewDivDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((588, 403))
		self.panel_3 = wx.Panel(self, wx.ID_ANY)
		self.text_ctrl_1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.choice_1 = wx.Choice(self.panel_3, wx.ID_ANY, choices=["N/A"])
		self.choice_2 = wx.Choice(self.panel_3, wx.ID_ANY, choices=["N/A"])
		self.radio_box_1 = wx.RadioBox(self.panel_3, wx.ID_ANY, "", choices=["Male", "Female"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
		self.cancel_button = wx.Button(self.panel_3, wx.ID_ANY, "Cancel")
		self.next_button = wx.Button(self.panel_3, wx.ID_ANY, "Next")
		self.panel_4 = wx.Panel(self, wx.ID_ANY)
		self.cancel_button_copy = wx.Button(self.panel_4, wx.ID_ANY, "Cancel")
		self.next_button_copy = wx.Button(self.panel_4, wx.ID_ANY, "Next")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: NewDivDialog.__set_properties
		self.SetTitle("New Division")
		self.SetSize((588, 403))
		self.choice_1.SetSelection(0)
		self.choice_2.SetSelection(0)
		self.radio_box_1.SetSelection(0)
		self.panel_4.Hide()
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: NewDivDialog.__do_layout
		sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
		grid_sizer_3 = wx.FlexGridSizer(1, 2, 10, 10)
		sizer_5 = wx.BoxSizer(wx.VERTICAL)
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		grid_sizer_2 = wx.FlexGridSizer(4, 2, 10, 10)
		label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, "Division Name", style=wx.ALIGN_RIGHT)
		grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
		grid_sizer_2.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
		label_2 = wx.StaticText(self.panel_3, wx.ID_ANY, "Belt", style=wx.ALIGN_RIGHT)
		grid_sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
		grid_sizer_2.Add(self.choice_1, 0, 0, 0)
		label_3 = wx.StaticText(self.panel_3, wx.ID_ANY, "Age", style=wx.ALIGN_RIGHT)
		grid_sizer_2.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
		grid_sizer_2.Add(self.choice_2, 0, 0, 0)
		label_4 = wx.StaticText(self.panel_3, wx.ID_ANY, "Gender", style=wx.ALIGN_RIGHT)
		grid_sizer_2.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
		grid_sizer_2.Add(self.radio_box_1, 0, 0, 0)
		grid_sizer_2.AddGrowableCol(1)
		sizer_5.Add(grid_sizer_2, 1, wx.ALL | wx.EXPAND, 40)
		sizer_6.Add(self.cancel_button, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_6.Add(self.next_button, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_5.Add(sizer_6, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 10)
		self.panel_3.SetSizer(sizer_5)
		sizer_4.Add(self.panel_3, 1, wx.EXPAND, 0)
		grid_sizer_3.Add((0, 0), 0, 0, 0)
		grid_sizer_3.AddGrowableCol(1)
		sizer_1.Add(grid_sizer_3, 1, wx.ALL | wx.EXPAND, 40)
		sizer_7.Add(self.cancel_button_copy, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_7.Add(self.next_button_copy, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
		sizer_1.Add(sizer_7, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 10)
		self.panel_4.SetSizer(sizer_1)
		sizer_4.Add(self.panel_4, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_4)
		self.Layout()
		# end wxGlade

# end of class NewDivDialog
